In [2]:
import Symbolics
#import SymbolicUtils
import LinearAlgebra

In [3]:
function pauli_x(_tmp)
    _00 = Symbol("X_00_", "$_tmp")
    _01 = Symbol("X_01_", "$_tmp")
    _10 = Symbol("X_10_", "$_tmp")
    _11 = Symbol("X_11_", "$_tmp")
    
    #transpose(reshape((Symbolics.@variables $_00::Complex $_01::Complex $_10::Complex $_11::Complex ),2,2))
    _00 = Symbolics.@variables $_00::Complex
    _01 = Symbolics.@variables $_01::Complex
    _10 = Symbolics.@variables $_10::Complex
    _11 = Symbolics.@variables $_11::Complex
    return [_00 _01;_10 _11]
    
    #Symbolics.@variables X_"00__tmp"replace("_tmp", _tmp)::Complex X_01_tmp::Complex X_10_tmp::Complex X_11_tmp::Complex
    #return [X_00_tmp X_01_tmp; X_10_tmp X_11_tmp]
end
function pauli_y()
    return Symbolics.variable(:Y, 1,2, T=ComplexF64)::ComplexF64
end
function pauli_z()
    return Symbolics.variables(:Z, 1:2, 1:2)
end

pauli_z (generic function with 1 method)

In [4]:
bb = pauli_x(:a)
bb


2×2 Matrix{Complex{Symbolics.Num}}:
 X_00_a  X_01_a
 X_10_a  X_11_a

In [6]:
typeof(bb)

Matrix{Complex{Num}} (alias for Array{Complex{Symbolics.Num}, 2})

In [7]:
b = Symbolics.@variables b_1 b_2

2-element Vector{Symbolics.Num}:
 b_1
 b_2

In [8]:
typeof(b)

Vector{Num} (alias for Array{Symbolics.Num, 1})

In [9]:
bb*b

2-element Vector{Complex{Symbolics.Num}}:
 b_1*real(X_00_a) + b_2*real(X_01_a) + (b_1*imag(X_00_a) + b_2*imag(X_01_a))*im
 b_1*real(X_10_a) + b_2*real(X_11_a) + (b_1*imag(X_10_a) + b_2*imag(X_11_a))*im