In [1]:
import Symbolics
import LinearAlgebra

In [2]:
function pauli_x(_tmp)
    _00 = Symbol("X_00_", "$_tmp")
    _01 = Symbol("X_01_", "$_tmp")
    _10 = Symbol("X_10_", "$_tmp")
    _11 = Symbol("X_11_", "$_tmp")
    
    #transpose(reshape((Symbolics.@variables $_00::Complex $_01::Complex $_10::Complex $_11::Complex ),2,2))
    _00 = Symbolics.@variables $_00::Complex
    _01 = Symbolics.@variables $_01::Complex
    _10 = Symbolics.@variables $_10::Complex
    _11 = Symbolics.@variables $_11::Complex
    return [_00 _01;_10 _11]
    
    #Symbolics.@variables X_"00__tmp"replace("_tmp", _tmp)::Complex X_01_tmp::Complex X_10_tmp::Complex X_11_tmp::Complex
    #return [X_00_tmp X_01_tmp; X_10_tmp X_11_tmp]
end
function pauli_y()
    _00 = Symbol("Y_00_", "$_tmp")
    _01 = Symbol("Y_01_", "$_tmp")
    _10 = Symbol("Y_10_", "$_tmp")
    _11 = Symbol("Y_11_", "$_tmp")
    
    #transpose(reshape((Symbolics.@variables $_00::Complex $_01::Complex $_10::Complex $_11::Complex ),2,2))
    _00 = Symbolics.@variables $_00::Complex
    _01 = Symbolics.@variables $_01::Complex
    _10 = Symbolics.@variables $_10::Complex
    _11 = Symbolics.@variables $_11::Complex
    return [_00 _01;_10 _11]
end
function pauli_z()
    _00 = Symbol("Z_00_", "$_tmp")
    _01 = Symbol("Z_01_", "$_tmp")
    _10 = Symbol("Z_10_", "$_tmp")
    _11 = Symbol("Z_11_", "$_tmp")
    
    #transpose(reshape((Symbolics.@variables $_00::Complex $_01::Complex $_10::Complex $_11::Complex ),2,2))
    _00 = Symbolics.@variables $_00::Complex
    _01 = Symbolics.@variables $_01::Complex
    _10 = Symbolics.@variables $_10::Complex
    _11 = Symbolics.@variables $_11::Complex
    return [_00 _01;_10 _11]
end

pauli_z (generic function with 1 method)

In [3]:
phi = Symbolics.@variables phi_1::Complex phi_2::Complex
phi = [phi_1; phi_2]

2-element Vector{Complex{Symbolics.Num}}:
 phi_1
 phi_2

In [4]:
theta = pauli_x(:A)*phi

2-element Vector{Complex{Symbolics.Num}}:
 -imag(phi_1)*imag(X_00_A) + real(X_01_A)*real(phi_2) + real(X_00_A)*real(phi_1) - imag(X_01_A)*imag(phi_2) + im*(imag(phi_1)*real(X_00_A) + real(X_01_A)*imag(phi_2) + real(phi_2)*imag(X_01_A) + real(phi_1)*imag(X_00_A))
 -imag(phi_1)*imag(X_10_A) + real(phi_2)*real(X_11_A) + real(phi_1)*real(X_10_A) - imag(X_11_A)*imag(phi_2) + im*(imag(phi_1)*real(X_10_A) + real(phi_2)*imag(X_11_A) + real(phi_1)*imag(X_10_A) + real(X_11_A)*imag(phi_2))

In [5]:
Symbolics.substitute(phi, Dict([phi[1] => 0, phi_2 => 1]))

2-element Vector{Complex{Symbolics.Num}}:
 phi_1
 phi_2

In [6]:
Symbolics.substitute(phi, phi_1.re=>0)

2-element Vector{Complex{Symbolics.Num}}:
 phi_1
 phi_2

In [7]:
Symbolics.fixpoint_sub(phi, phi_1.re=>0)

2-element Vector{Complex{Symbolics.Num}}:
 phi_1
 phi_2

In [8]:
Symbolics.substitute(theta[1], Dict([phi_1.im => 0, phi_1.re => 0]))

real(X_01_A)*real(phi_2) - imag(X_01_A)*imag(phi_2) + im*(real(X_01_A)*imag(phi_2) + real(phi_2)*imag(X_01_A))

In [41]:
Symbolics.substitute(theta[1], Dict([X_01_A.re => 0]))

LoadError: UndefVarError: `X_01_A` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [33]:
Symbolics.get_variables(theta[1])

SymbolicUtils.BasicSymbolic[]

In [36]:
typeof(theta[1])

Complex{Symbolics.Num}

In [16]:
println(Main.varinfo(@; all=true, imported=true))

LoadError: MethodError: no method matching varinfo(::String; all::Bool, imported::Bool)
The function `varinfo` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  varinfo(::Regex; kwargs...)
   @ InteractiveUtils C:\Users\oahre\.julia\juliaup\julia-1.11.2+0.x64.w64.mingw32\share\julia\stdlib\v1.11\InteractiveUtils\src\InteractiveUtils.jl:86
  varinfo(::Module, ::Regex; all, imported, recursive, sortby, minsize)
   @ InteractiveUtils C:\Users\oahre\.julia\juliaup\julia-1.11.2+0.x64.w64.mingw32\share\julia\stdlib\v1.11\InteractiveUtils\src\InteractiveUtils.jl:45
  varinfo(::Module; ...)
   @ InteractiveUtils C:\Users\oahre\.julia\juliaup\julia-1.11.2+0.x64.w64.mingw32\share\julia\stdlib\v1.11\InteractiveUtils\src\InteractiveUtils.jl:45
  ...


In [43]:
Base.names(Main; all=true, imported=true)

26-element Vector{Symbol}:
 Symbol("##meta#59")
 Symbol("#eval")
 Symbol("#include")
 Symbol("#pauli_x")
 Symbol("#pauli_y")
 Symbol("#pauli_z")
 :Base
 :Core
 :IJulia
 :In
 :LinearAlgebra
 :Main
 :Out
 :Symbolics
 :ans
 :clear_history
 :docs
 :eval
 :include
 :pauli_x
 :pauli_y
 :pauli_z
 :phi
 :phi_1
 :phi_2
 :theta