In [1]:
using Symbolics

In [2]:
function pauli_x(_tmp)
    _00 = Symbol("X_00_", "$_tmp")
    _01 = Symbol("X_01_", "$_tmp")
    _10 = Symbol("X_10_", "$_tmp")
    _11 = Symbol("X_11_", "$_tmp")
    
    #transpose(reshape((Symbolics.@variables $_00::Complex $_01::Complex $_10::Complex $_11::Complex ),2,2))
    _00 = @variables $_00::Complex
    _01 = @variables $_01::Complex
    _10 = @variables $_10::Complex
    _11 = @variables $_11::Complex
    return [_00 _01;_10 _11]
    
    #Symbolics.@variables X_"00__tmp"replace("_tmp", _tmp)::Complex X_01_tmp::Complex X_10_tmp::Complex X_11_tmp::Complex
    #return [X_00_tmp X_01_tmp; X_10_tmp X_11_tmp]
end
function pauli_y()
    _00 = Symbol("Y_00_", "$_tmp")
    _01 = Symbol("Y_01_", "$_tmp")
    _10 = Symbol("Y_10_", "$_tmp")
    _11 = Symbol("Y_11_", "$_tmp")
    
    #transpose(reshape((Symbolics.@variables $_00::Complex $_01::Complex $_10::Complex $_11::Complex ),2,2))
    _00 = @variables $_00::Complex
    _01 = @variables $_01::Complex
    _10 = @variables $_10::Complex
    _11 = @variables $_11::Complex
    return [_00 _01;_10 _11]
end
function pauli_z()
    _00 = Symbol("Z_00_", "$_tmp")
    _01 = Symbol("Z_01_", "$_tmp")
    _10 = Symbol("Z_10_", "$_tmp")
    _11 = Symbol("Z_11_", "$_tmp")
    
    #transpose(reshape((Symbolics.@variables $_00::Complex $_01::Complex $_10::Complex $_11::Complex ),2,2))
    _00 = @variables $_00::Complex
    _01 = @variables $_01::Complex
    _10 = @variables $_10::Complex
    _11 = @variables $_11::Complex
    return [_00 _01;_10 _11]
end

pauli_z (generic function with 1 method)

In [3]:
phi = @variables phi_1::Complex phi_2::Complex
phi = [phi_1; phi_2]

2-element Vector{Complex{Num}}:
 phi_1
 phi_2

In [4]:
theta = pauli_x(:A)*phi

2-element Vector{Complex{Num}}:
 -imag(phi_1)*imag(X_00_A) + real(X_01_A)*real(phi_2) + real(X_00_A)*real(phi_1) - imag(X_01_A)*imag(phi_2) + im*(imag(phi_1)*real(X_00_A) + real(X_01_A)*imag(phi_2) + real(phi_2)*imag(X_01_A) + real(phi_1)*imag(X_00_A))
 -imag(phi_1)*imag(X_10_A) + real(phi_2)*real(X_11_A) + real(phi_1)*real(X_10_A) - imag(X_11_A)*imag(phi_2) + im*(imag(phi_1)*real(X_10_A) + real(phi_2)*imag(X_11_A) + real(phi_1)*imag(X_10_A) + real(X_11_A)*imag(phi_2))

In [7]:
substitute(phi, Dict([phi[1] => 0, phi_2 => 1]))

2-element Vector{Complex{Num}}:
 phi_1
 phi_2

In [8]:
substitute(phi, phi_1.re=>0)

2-element Vector{Complex{Num}}:
 phi_1
 phi_2

In [9]:
fixpoint_sub(phi, phi_1.re=>0)

LoadError: UndefVarError: `fixpoint_sub` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [10]:
substitute(theta[1], Dict([phi_1.im => 0, phi_1.re => 0]))

real(X_01_A)*real(phi_2) - imag(X_01_A)*imag(phi_2) + im*(real(X_01_A)*imag(phi_2) + real(phi_2)*imag(X_01_A))

In [13]:
Symbolics.get_variables(phi[1])

SymbolicUtils.BasicSymbolic[]